#CONFIGURATION FILE
#Source directory to backup

SOURCE_DIR="./files"

#Local Backup Directory

DESTINATION_DIR="./backup"

#Remote Backup Directory

REMOTE_BACKUP_DIR="./remote-backup"

#Log Directory Location

LOG_DIR="./log"

#Log File Location

LOG_FILE="./backup.log"

#Retention Days

RETENTION_DAYS=7

#Comprestion Type

COMPRESSION="tar.gz"

#Backup Schedule

BACKUP_TIME="21:00"

#Backup File Prefix

BACKUP_PREFIX="linux_backup"

#Enable remote backup

ENABLE_REMOTE_BACKUP="yes"


