name: Automated Linux Backup and Recovery System CI Pipeline


on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubantu-latest

    steps:
    - name: Test CI
      run: echo "CI is working Successfully"
      
